### ISSUE TITLE
Can't open Lecture 02 notebook

### ISSUE THREAD

**Issue by awe2** [gnarayan/ast596_2020_Spring#150]
Both myself and a friend with a fresh clone can't open week 02 lecture materials with error:

"Unreadable Notebook: C:\Users\qwsaz\Spring 2020\ast596_2020_Spring\lecture\02\week02.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "c...',)"

Other notebooks open fine

OS: Windows 10

**Comment by gnarayan** [comment]
Fixed
